export const ALL_PERMISSIONS = [
  "USER-SHOW",
  "USER-ADD",
  "USER-EDIT",
  "USER-DELETE",
  "USER-ASSIGN",

  "MOBILE-RECHARGE",
  "DTH-RECHARGE",
  "ELECTRICITY-PAYMENT",
  "GAS-PAYMENT",

  "WALLET-SHOW",
  "WALLET-ADD",
  "WALLET-EDIT",
  "WALLET-DELETE",
  "WALLET-REPORT",

  "TRANSACTION-REPORT",
  "DAY-RECHARGE",
  "DAY-SALES",

  "COMMISSION-SHOW",
  "COMMISSION-ADD",
  "COMMISSION-EDIT",
  "COMMISSION-DELETE",

  "ROLE-SHOW",
  "ROLE-ADD",
  "ROLE-EDIT",
  "ROLE-DELETE",
];